setopt alwaystoend
setopt autonamedirs
setopt autopushd
setopt nobeep
setopt completealiases
setopt extendedhistory
setopt histexpiredupsfirst
setopt histverify
setopt incappendhistory
setopt interactive
setopt monitor
setopt promptsubst
setopt zle
